import type { Sector } from "./types";

function score(parts: { momentum: number; trendStrength: number; breadth: number; valuation: number; flows: number; risk: number }) {
  const total = Math.round(
    parts.momentum * 0.25 +
    parts.trendStrength * 0.2 +
    parts.breadth * 0.15 +
    parts.valuation * 0.15 +
    parts.flows * 0.15 +
    parts.risk * 0.1,
  );
  return { ...parts, total };
}

export const sectors: Sector[] = [
  {
    symbol: "XLK", name: "Technology", weight: 31.2,
    change1d: 0.7, change1m: 4.4, changeYtd: 32.1, trend: "bull",
    description: "Sektor technologii informacyjnej — software, półprzewodniki, hardware. Lider hossy AI.",
    topHoldings: ["AAPL", "MSFT", "NVDA", "AVGO"],
    pe: 32, breadth: 78, relativeStrength: 42,
    rating: "Overweight",
    catalysts: ["Wydatki capex na AI", "Cykl wymiany sprzętu", "Obniżki stóp Fed"],
    risks: ["Wycena rozciągnięta", "Koncentracja w 5 spółkach", "Regulacje antymonopolowe"],
    score: score({ momentum: 88, trendStrength: 82, breadth: 78, valuation: 28, flows: 75, risk: 55 }),
  },
  {
    symbol: "XLF", name: "Financials", weight: 13.0,
    change1d: 0.3, change1m: 2.6, changeYtd: 28.4, trend: "bull",
    description: "Banki, ubezpieczenia, broker-dealerzy. Beneficjent stromej krzywej rentowności.",
    topHoldings: ["BRK.B", "JPM", "V", "MA"],
    pe: 16, breadth: 72, relativeStrength: 28,
    rating: "Overweight",
    catalysts: ["Dereregulacja", "Wzrost NIM", "Konsolidacja sektora"],
    risks: ["Pogorszenie kredytu", "Recesja"],
    score: score({ momentum: 78, trendStrength: 74, breadth: 72, valuation: 70, flows: 68, risk: 60 }),
  },
  {
    symbol: "XLV", name: "Healthcare", weight: 11.6,
    change1d: 0.1, change1m: -0.4, changeYtd: 7.8, trend: "neutral",
    description: "Farma, biotech, sprzęt medyczny, ubezpieczenia zdrowotne.",
    topHoldings: ["LLY", "UNH", "JNJ", "MRK"],
    pe: 18, breadth: 48, relativeStrength: -10,
    rating: "Neutral",
    catalysts: ["Pipeline GLP-1", "Starzenie się populacji"],
    risks: ["Negocjacje cen leków", "Polityka zdrowotna USA"],
    score: score({ momentum: 42, trendStrength: 48, breadth: 48, valuation: 62, flows: 50, risk: 70 }),
  },
  {
    symbol: "XLY", name: "Consumer Disc.", weight: 10.4,
    change1d: 0.5, change1m: 5.1, changeYtd: 19.6, trend: "bull",
    description: "Detal, motoryzacja, e-commerce, dobra luksusowe — cykliczny.",
    topHoldings: ["AMZN", "TSLA", "HD", "MCD"],
    pe: 27, breadth: 65, relativeStrength: 18,
    rating: "Overweight",
    catalysts: ["Silny konsument USA", "Sezon świąteczny"],
    risks: ["Wzrost zadłużenia kart kredytowych", "Inflacja usług"],
    score: score({ momentum: 76, trendStrength: 70, breadth: 65, valuation: 38, flows: 64, risk: 55 }),
  },
  {
    symbol: "XLC", name: "Communication", weight: 9.0,
    change1d: 0.4, change1m: 3.8, changeYtd: 28.0, trend: "bull",
    description: "Media, social, telekomy. Zdominowany przez META i GOOGL.",
    topHoldings: ["META", "GOOGL", "GOOG", "NFLX"],
    pe: 22, breadth: 58, relativeStrength: 30,
    rating: "Overweight",
    catalysts: ["Reklama AI", "Cięcia kosztów big tech"],
    risks: ["Regulacje antymonopolowe", "Konkurencja TikTok"],
    score: score({ momentum: 80, trendStrength: 76, breadth: 58, valuation: 56, flows: 62, risk: 60 }),
  },
  {
    symbol: "XLI", name: "Industrials", weight: 8.4,
    change1d: 0.2, change1m: 1.6, changeYtd: 21.0, trend: "bull",
    description: "Lotnictwo, obronność, transport, maszyny. Beneficjent reshoringu.",
    topHoldings: ["GE", "RTX", "CAT", "UNP"],
    pe: 20, breadth: 70, relativeStrength: 12,
    rating: "Overweight",
    catalysts: ["Reshoring", "Wydatki obronne", "Infrastructure Bill"],
    risks: ["Spowolnienie globalne", "PMI < 50"],
    score: score({ momentum: 68, trendStrength: 70, breadth: 70, valuation: 60, flows: 60, risk: 65 }),
  },
  {
    symbol: "XLP", name: "Staples", weight: 5.7,
    change1d: -0.1, change1m: -0.6, changeYtd: 12.4, trend: "neutral",
    description: "Dobra pierwszej potrzeby, defensywny, niska beta.",
    topHoldings: ["PG", "COST", "WMT", "KO"],
    pe: 22, breadth: 52, relativeStrength: -22,
    rating: "Neutral",
    catalysts: ["Risk-off", "Spadek stóp"],
    risks: ["Słabsza marża", "Konkurencja private label"],
    score: score({ momentum: 38, trendStrength: 44, breadth: 52, valuation: 50, flows: 42, risk: 80 }),
  },
  {
    symbol: "XLE", name: "Energy", weight: 3.4,
    change1d: -0.4, change1m: 0.4, changeYtd: 18.0, trend: "neutral",
    description: "Naftowo-gazowy, integrowany — zależny od ropy i geopolityki.",
    topHoldings: ["XOM", "CVX", "COP", "EOG"],
    pe: 12, breadth: 50, relativeStrength: -8,
    rating: "Neutral",
    catalysts: ["Cięcia OPEC+", "Geopolityka Bliskiego Wschodu"],
    risks: ["Recesja → spadek popytu", "Transformacja energetyczna"],
    score: score({ momentum: 50, trendStrength: 48, breadth: 50, valuation: 84, flows: 48, risk: 50 }),
  },
  {
    symbol: "XLU", name: "Utilities", weight: 2.6,
    change1d: 0.0, change1m: -1.2, changeYtd: 24.4, trend: "neutral",
    description: "Energetyka regulowana — proxy obligacji, beneficjent AI capex.",
    topHoldings: ["NEE", "SO", "DUK", "VST"],
    pe: 19, breadth: 55, relativeStrength: 6,
    rating: "Neutral",
    catalysts: ["Zapotrzebowanie AI na prąd", "Spadek stóp"],
    risks: ["Wzrost rentowności obligacji", "Capex regulacyjny"],
    score: score({ momentum: 58, trendStrength: 54, breadth: 55, valuation: 58, flows: 56, risk: 75 }),
  },
  {
    symbol: "XLRE", name: "Real Estate", weight: 2.3,
    change1d: -0.2, change1m: -2.0, changeYtd: 8.2, trend: "bear",
    description: "REIT-y — biura, magazyny, centra handlowe, data centers.",
    topHoldings: ["PLD", "AMT", "EQIX", "WELL"],
    pe: 36, breadth: 35, relativeStrength: -28,
    rating: "Underweight",
    catalysts: ["Spadek rentowności 10Y", "Boom data centers"],
    risks: ["Refinansowanie biur", "CRE delinquency"],
    score: score({ momentum: 28, trendStrength: 32, breadth: 35, valuation: 30, flows: 35, risk: 45 }),
  },
  {
    symbol: "XLB", name: "Materials", weight: 2.4,
    change1d: 0.1, change1m: 1.0, changeYtd: 9.4, trend: "neutral",
    description: "Chemia, metale, opakowania — wczesny cykl, zależny od Chin.",
    topHoldings: ["LIN", "SHW", "FCX", "ECL"],
    pe: 21, breadth: 50, relativeStrength: -14,
    rating: "Neutral",
    catalysts: ["Stymulus Chiny", "Reshoring", "Słabszy dolar"],
    risks: ["Słabość PMI", "Spadek cen metali"],
    score: score({ momentum: 46, trendStrength: 50, breadth: 50, valuation: 52, flows: 48, risk: 60 }),
  },
];
