import type { Tactic } from "./types";

export const tactics: Tactic[] = [
  {
    id: "trend-following",
    name: "Trend Following na ETF szerokiego rynku",
    description: "Pozostań long, gdy SPY > MA200 i nachylenie MA50 jest dodatnie.",
    entryRules: [
      "Cena SPY > MA200",
      "MA50 rośnie 5+ sesji z rzędu",
      "VIX < 20",
    ],
    exitRules: [
      "Cena SPY zamyka pod MA200",
      "VIX > 28 i MA50 spada",
    ],
    worksWhen: "Trwałe trendy wzrostowe, niska zmienność, supportywne stopy.",
    failsWhen: "Choppy markets, gwałtowne korekty z VIX-spike, kryzysy płynności.",
    risk: "średnie",
    backtest: { winRate: 58, avgRR: 2.4, trades: 142 },
    observations: [
      "Najlepsze sesje: po dotknięciu MA50 z odbiciem.",
      "Większość obsunięć w okresie wrzesień–październik.",
    ],
    horizon: "długi",
  },
  {
    id: "mean-reversion",
    name: "Mean Reversion na S&P (RSI < 30)",
    description: "Krótka pozycja kontrtrendowa: kupuj panikę, sprzedaj odbicie.",
    entryRules: [
      "RSI(2) na SPY < 5",
      "Cena 2%+ pod MA10",
      "VIX > 25",
    ],
    exitRules: [
      "RSI(2) > 70 lub +3% od wejścia",
      "Stop: -2.5% od wejścia",
    ],
    worksWhen: "Zmienny rynek bez bear-markeu, szybkie panikujące spadki.",
    failsWhen: "Bear market trendowy, wydarzenia kredytowe, czarne łabędzie.",
    risk: "wysokie",
    backtest: { winRate: 71, avgRR: 1.4, trades: 88 },
    observations: ["Działa lepiej w ETF szerokich niż na pojedynczych spółkach."],
    horizon: "krótki",
  },
  {
    id: "sector-rotation",
    name: "Rotacja sektorowa (Top-3 momentum)",
    description: "Co miesiąc kupuj 3 najsilniejsze sektory S&P (3M momentum).",
    entryRules: ["Pierwsza sesja miesiąca", "Top 3 sektory wg 3M zwrotu"],
    exitRules: ["Koniec miesiąca — rotacja", "Sektor wypada z Top 5"],
    worksWhen: "Wyraźne fazy cyklu, dyspersja między sektorami.",
    failsWhen: "Rynek bez kierunku, mean reversion sektorowy.",
    risk: "średnie",
    backtest: { winRate: 62, avgRR: 1.8, trades: 60 },
    observations: ["Lepsze wyniki w drugiej połowie cyklu wzrostowego."],
    horizon: "średni",
  },
  {
    id: "dividend-growth",
    name: "Dividend Growth (Aristocrats DCA)",
    description: "Comiesięczne DCA do spółek z 25+ lat wzrostu dywidendy.",
    entryRules: ["Stała kwota co miesiąc", "Tylko spółki z indeksu Aristocrats"],
    exitRules: ["Cięcie dywidendy", "Dywidenda < 1.5%"],
    worksWhen: "Każde otoczenie — strategia długoterminowa.",
    failsWhen: "Krótkie horyzonty (< 5 lat), pogoń za zwrotem.",
    risk: "niskie",
    backtest: { winRate: 84, avgRR: 1.2, trades: 240 },
    observations: ["Ogranicza obsunięcia, ale kosztem upside w hossie tech."],
    horizon: "długi",
  },
  {
    id: "etf-dca",
    name: "ETF DCA na VTI/QQQ",
    description: "Comiesięczne uśrednianie ceny w szerokim rynku USA.",
    entryRules: ["1 dzień miesiąca", "Stała kwota niezależnie od ceny"],
    exitRules: ["Cel finansowy", "Zmiana planu życiowego"],
    worksWhen: "Każde otoczenie, długi horyzont.",
    failsWhen: "Próby market timingu zamiast trzymania planu.",
    risk: "niskie",
    backtest: { winRate: 78, avgRR: 1.6, trades: 360 },
    observations: ["Najprostsza i najskuteczniejsza dla większości."],
    horizon: "długi",
  },
  {
    id: "defensive-hedge",
    name: "Defensywny hedge (TLT + GLD)",
    description: "20% portfela w TLT i 10% w GLD jako stabilizator.",
    entryRules: [
      "Kiedy VIX < 15 (tanio kupić ubezpieczenie)",
      "Po sygnałach ostrzegawczych makro",
    ],
    exitRules: ["VIX > 30 — częściowa realizacja", "Powrót do equity, gdy spread korekt > 15%"],
    worksWhen: "Risk-off, panika, kryzysy bankowe.",
    failsWhen: "Stagflacja (TLT i GLD mogą się rozjechać).",
    risk: "średnie",
    backtest: { winRate: 54, avgRR: 1.9, trades: 32 },
    observations: ["TLT czuły na stopy — wymaga aktywnego zarządzania."],
    horizon: "średni",
  },
];
