import type { MacroIndicator } from "./types";

export const macroIndicators: MacroIndicator[] = [
  {
    id: "us-cpi", name: "CPI (USA, YoY)", nameEn: "Consumer Price Index",
    region: "USA", value: 2.6, unit: "%", change: -0.1, asOf: "2025-04-15", interpretation: "positive",
    note: "Inflacja schładza się w kierunku celu 2%.",
    category: "Inflacja", trend: "falling", target: 2.0,
    description: "Wskaźnik inflacji konsumenckiej — średnia zmiana cen koszyka dóbr i usług w skali roku.",
    whyItMatters: "Główny wskaźnik dla decyzji Fed o stopach. Niższe CPI = większa szansa na obniżki.",
    impact: "Spadek CPI wspiera akcje (zwłaszcza growth) i obligacje. Wzrost — odwrotnie.",
    source: "BLS",
  },
  {
    id: "us-cpi-core", name: "CPI Core (USA, YoY)", nameEn: "Core CPI (ex food & energy)",
    region: "USA", value: 3.2, unit: "%", change: -0.1, asOf: "2025-04-15", interpretation: "neutral",
    category: "Inflacja", trend: "falling", target: 2.0,
    description: "CPI z wyłączeniem zmiennych cen żywności i energii — pokazuje trwały trend inflacji.",
    whyItMatters: "Fed śledzi przede wszystkim core CPI/PCE, bo lepiej oddają inflację bazową.",
    impact: "Sticky core inflation = później obniżki = presja na akcje i długie obligacje.",
    source: "BLS",
  },
  {
    id: "us-pce", name: "PCE Core (USA, YoY)", nameEn: "Personal Consumption Expenditures",
    region: "USA", value: 2.8, unit: "%", change: -0.1, asOf: "2025-04-26", interpretation: "positive",
    category: "Inflacja", trend: "falling", target: 2.0,
    description: "Preferowany przez Fed wskaźnik inflacji bazowej.",
    whyItMatters: "Bezpośredni input do funkcji reakcji Fed.",
    impact: "Spadek poniżej 2.5% otwiera drogę do obniżek stóp.",
    source: "BEA",
  },
  {
    id: "us-fed", name: "Fed Funds Rate", nameEn: "Federal Funds Rate",
    region: "USA", value: 4.50, unit: "%", change: -0.25, asOf: "2025-05-02", interpretation: "positive",
    note: "Cykl obniżek wciąż otwarty.",
    category: "Stopy", trend: "falling",
    description: "Stopa procentowa, po której banki pożyczają sobie nawzajem na noc — kotwica całej krzywej.",
    whyItMatters: "Definiuje koszt pieniądza w gospodarce, wpływa na DCF spółek i wycenę aktywów.",
    impact: "Obniżki = wyższe wyceny PE, wsparcie dla growth, słabszy USD.",
    source: "FOMC",
  },
  {
    id: "us-2y", name: "US 2Y Yield", nameEn: "2-Year Treasury Yield",
    region: "USA", value: 4.05, unit: "%", change: -0.05, asOf: "2025-05-13", interpretation: "positive",
    category: "Obligacje", trend: "falling",
    description: "Rentowność 2-letnich obligacji USA — najbliższa oczekiwaniom co do stóp Fed.",
    whyItMatters: "Spadek = rynek wycenia szybsze obniżki Fed.",
    impact: "Niższy 2Y wspiera akcje i mocno growth.",
  },
  {
    id: "us-10y", name: "US 10Y Yield", nameEn: "10-Year Treasury Yield",
    region: "USA", value: 4.32, unit: "%", change: 0.06, asOf: "2025-05-13", interpretation: "neutral",
    category: "Obligacje", trend: "stable",
    description: "Rentowność 10-letnich obligacji skarbowych USA — globalna stopa wolna od ryzyka.",
    whyItMatters: "Benchmark dla wycen DCF i hipotek; kluczowa dla long-duration assets (tech, REIT).",
    impact: "10Y > 4.5% historycznie tworzy presję na akcje wzrostowe.",
  },
  {
    id: "us-spread", name: "Spread 10Y-2Y", nameEn: "Yield Curve 10Y-2Y",
    region: "USA", value: 0.27, unit: "pp", change: 0.10, asOf: "2025-05-13", interpretation: "positive",
    category: "Obligacje", trend: "rising",
    description: "Różnica rentowności 10Y i 2Y — krzywa rentowności. Inwersja (ujemna) historycznie poprzedza recesję.",
    whyItMatters: "Stromienie krzywej (rosnąca) sygnalizuje koniec cyklu zacieśniania.",
    impact: "Steepener = pozytywne dla banków (XLF), neutralne dla S&P.",
  },
  {
    id: "us-unemp", name: "Bezrobocie USA", nameEn: "Unemployment Rate",
    region: "USA", value: 4.1, unit: "%", change: 0.0, asOf: "2025-05-01", interpretation: "neutral",
    category: "Rynek pracy", trend: "stable",
    description: "Odsetek osób aktywnych zawodowo, które szukają pracy.",
    whyItMatters: "Sahm Rule: wzrost o 0.5pp od dołka = sygnał recesji.",
    impact: "Rosnące bezrobocie = obniżki Fed (pozytyw dla obligacji), ale ryzyko recesji.",
    source: "BLS",
  },
  {
    id: "us-nfp", name: "NFP (Non-Farm Payrolls)", nameEn: "Non-Farm Payrolls",
    region: "USA", value: 175, unit: "tys.", change: -25, asOf: "2025-05-03", interpretation: "neutral",
    category: "Rynek pracy", trend: "falling",
    description: "Liczba nowych miejsc pracy poza rolnictwem w danym miesiącu.",
    whyItMatters: "Najważniejszy miesięczny odczyt makro — porusza rynkami w sekundach.",
    impact: "<100k = ryzyko recesji, >250k = inflacja płacowa, presja na Fed.",
    source: "BLS",
  },
  {
    id: "us-ism", name: "ISM Manufacturing PMI", nameEn: "ISM Manufacturing PMI",
    region: "USA", value: 49.2, unit: "pkt", change: 0.4, asOf: "2025-05-01", interpretation: "neutral",
    category: "Aktywność", trend: "rising", target: 50,
    description: "Wskaźnik aktywności w przemyśle USA. >50 = ekspansja, <50 = kontrakcja.",
    whyItMatters: "Wyprzedzający wskaźnik koniunktury — koreluje z zyskami spółek cyklicznych.",
    impact: "Wzrost ponad 50 wspiera Industrials, Materials, small-caps.",
  },
  {
    id: "vix", name: "VIX", nameEn: "CBOE Volatility Index",
    region: "USA", value: 14.8, unit: "pkt", change: -0.6, asOf: "2025-05-13", interpretation: "positive",
    note: "Rynek spokojny, brak strachu.",
    category: "Sentyment", trend: "falling",
    description: "Indeks zmienności S&P 500 oparty o opcje 30-dniowe — indeks strachu.",
    whyItMatters: "Niski VIX = optymizm i ryzyko samozadowolenia. Wysoki = panika i okazje.",
    impact: "VIX <15: faza spokoju. >25: alert. >35: panika.",
  },
  {
    id: "ecb", name: "ECB Rate", nameEn: "ECB Deposit Rate",
    region: "Europa", value: 3.25, unit: "%", change: -0.25, asOf: "2025-04-30", interpretation: "positive",
    category: "Stopy", trend: "falling",
    description: "Główna stopa procentowa Europejskiego Banku Centralnego.",
    whyItMatters: "Decyduje o koszcie kapitału w strefie euro, kursie EUR/USD i wycenach europejskich akcji.",
    impact: "Obniżki ECB = słabsze EUR, wsparcie dla eksporterów (DAX, CAC).",
  },
  {
    id: "eu-cpi", name: "CPI (EU, YoY)", nameEn: "Eurozone HICP",
    region: "Europa", value: 2.2, unit: "%", change: -0.1, asOf: "2025-04-30", interpretation: "positive",
    category: "Inflacja", trend: "falling", target: 2.0,
    description: "Inflacja HICP w strefie euro.",
    whyItMatters: "Determinuje tempo obniżek ECB.",
    impact: "Spadek do celu 2% otwiera drogę do agresywnych cięć.",
  },
  {
    id: "eurusd", name: "EUR/USD", nameEn: "Euro-Dollar",
    region: "Global", value: 1.085, unit: "", change: 0.004, asOf: "2025-05-13", interpretation: "neutral",
    category: "Waluty", trend: "stable",
    description: "Najbardziej płynna para walutowa świata.",
    whyItMatters: "Mocny EUR = presja na eksporterów EU, wsparcie dla amerykańskich multinationals.",
    impact: ">1.10 wspiera europejskie akcje konsumpcyjne.",
  },
  {
    id: "dxy", name: "DXY", nameEn: "US Dollar Index",
    region: "Global", value: 103.2, unit: "pkt", change: -0.2, asOf: "2025-05-13", interpretation: "positive",
    note: "Słabszy dolar wspiera ryzykowne aktywa.",
    category: "Waluty", trend: "falling",
    description: "Indeks dolara względem koszyka 6 walut (EUR, JPY, GBP, CAD, SEK, CHF).",
    whyItMatters: "Słabszy USD = lepiej dla EM, surowców, złota i zysków US multinationals.",
    impact: "DXY <102 = strong tailwind dla GLD, EM, materiałów.",
  },
  {
    id: "wti", name: "Ropa WTI", nameEn: "WTI Crude Oil",
    region: "Global", value: 71.4, unit: "USD", change: -0.8, asOf: "2025-05-13", interpretation: "neutral",
    category: "Surowce", trend: "stable",
    description: "Cena baryłki ropy West Texas Intermediate.",
    whyItMatters: "Wpływa na inflację, marże airline'ów, sektor energetyczny.",
    impact: "Stabilne 65-80 USD: optymalne dla rynków. >90 = ryzyko inflacji.",
  },
  {
    id: "gold", name: "Złoto (USD/oz)", nameEn: "Gold Spot",
    region: "Global", value: 2685, unit: "USD", change: 12, asOf: "2025-05-13", interpretation: "positive",
    category: "Surowce", trend: "rising",
    description: "Cena uncji złota w USD.",
    whyItMatters: "Bezpieczna przystań, hedge na inflację i ryzyko geopolityczne.",
    impact: "Rosnące złoto + spadający DXY = klasyczny risk-off lub anty-USD.",
  },
];
