import type { Tactic } from "./types";

export const tactics: Tactic[] = [
  {
    id: "trend-following",
    name: "Trend Following na ETF szerokiego rynku",
    description: "Pozostań long, gdy SPY > MA200 i nachylenie MA50 jest dodatnie.",
    longDescription:
      "Klasyczna strategia podążania za trendem oparta o średnie kroczące. Zakłada, że trendy trwają dłużej niż się wydaje i kara za bycie poza rynkiem w hossie jest większa niż za drobne obsunięcia. Wykorzystuje proste filtry techniczne (MA200, MA50) oraz filtr zmienności (VIX) w celu unikania okresów paniki.",
    entryRules: ["Cena SPY > MA200", "MA50 rośnie 5+ sesji z rzędu", "VIX < 20"],
    exitRules: ["Cena SPY zamyka pod MA200", "VIX > 28 i MA50 spada"],
    worksWhen: "Trwałe trendy wzrostowe, niska zmienność, supportywne stopy.",
    failsWhen: "Choppy markets, gwałtowne korekty z VIX-spike, kryzysy płynności.",
    risk: "średnie",
    backtest: { winRate: 58, avgRR: 2.4, trades: 142 },
    observations: [
      "Najlepsze sesje: po dotknięciu MA50 z odbiciem.",
      "Większość obsunięć w okresie wrzesień–październik.",
    ],
    horizon: "długi",
    instruments: ["SPY", "VOO", "VTI", "QQQ"],
    parameters: [
      { name: "MA długa", value: "200 sesji", description: "Filtr trendu głównego." },
      { name: "MA krótka", value: "50 sesji", description: "Filtr momentum." },
      { name: "Próg VIX", value: "20 / 28", description: "Wejście / wyjście awaryjne." },
      { name: "Wielkość pozycji", value: "1× kapitał", description: "Bez dźwigni." },
    ],
    dependencies: [
      "Polityka monetarna Fed (cykl obniżek wspiera).",
      "Brak shocków geopolitycznych.",
      "Płynność rynku (TED spread, kredyt korporacyjny).",
    ],
    examples: [
      { date: "2023-04", setup: "SPY przebił MA200 po dezinflacji CPI", outcome: "+18% w 7 mies." },
      { date: "2024-08", setup: "Korekta w sierpniu, VIX 38 → wyjście", outcome: "Uniknięte -6% obsunięcie" },
    ],
    marketRegime: ["bull-low-vol", "risk-on", "post-Fed-pivot"],
    capitalRequirement: "Od 1 000 USD (jednostka SPY).",
    timeCommitment: "5 min dziennie po zamknięciu USA.",
    pros: ["Prosta i mechaniczna", "Niskie koszty transakcyjne", "Skuteczna w hossie"],
    cons: ["Spóźnione wejścia", "Whipsaw w bocznym rynku", "Wymaga dyscypliny"],
    related: ["sector-rotation", "etf-dca"],
    source: "Faber (2007) – A Quantitative Approach to Tactical Asset Allocation",
  },
  {
    id: "mean-reversion",
    name: "Mean Reversion na S&P (RSI < 30)",
    description: "Krótka pozycja kontrtrendowa: kupuj panikę, sprzedaj odbicie.",
    longDescription:
      "Strategia wykorzystująca skłonność rynku do gwałtownego odbicia po krótkoterminowej wyprzedaży. Bazuje na RSI(2) i odległości ceny od średniej kroczącej. Wymaga ścisłego stop-lossa, bo w bear markecie kontrtrend bywa zabójczy.",
    entryRules: ["RSI(2) na SPY < 5", "Cena 2%+ pod MA10", "VIX > 25"],
    exitRules: ["RSI(2) > 70 lub +3% od wejścia", "Stop: -2.5% od wejścia"],
    worksWhen: "Zmienny rynek bez bear-marketu, szybkie panikujące spadki.",
    failsWhen: "Bear market trendowy, wydarzenia kredytowe, czarne łabędzie.",
    risk: "wysokie",
    backtest: { winRate: 71, avgRR: 1.4, trades: 88 },
    observations: ["Działa lepiej w ETF szerokich niż na pojedynczych spółkach."],
    horizon: "krótki",
    instruments: ["SPY", "QQQ", "IWM"],
    parameters: [
      { name: "RSI okres", value: "2", description: "Bardzo czuły oscylator." },
      { name: "Próg wejścia", value: "RSI < 5" },
      { name: "Stop", value: "-2.5%" },
      { name: "Take profit", value: "RSI > 70 lub +3%" },
    ],
    dependencies: ["Główny trend wzrostowy", "VIX > 25 (panika)", "Płynność intraday"],
    examples: [
      { date: "2023-10", setup: "RSI(2)=3 po jastrzębim Fed", outcome: "+2.8% w 3 sesje" },
      { date: "2022-06", setup: "Próba w trendzie spadkowym", outcome: "Stop -2.5%" },
    ],
    marketRegime: ["choppy", "high-vol-short", "post-shock"],
    capitalRequirement: "Min. 5 000 USD ze względu na ścisłe stopy.",
    timeCommitment: "Aktywny monitoring intraday.",
    pros: ["Wysoki win rate", "Krótkie trzymanie pozycji"],
    cons: ["RR < 2", "Bardzo bolesne porażki w bear markecie"],
    related: ["trend-following"],
    source: "Connors – „Short Term Trading Strategies That Work"",
  },
  {
    id: "sector-rotation",
    name: "Rotacja sektorowa (Top-3 momentum)",
    description: "Co miesiąc kupuj 3 najsilniejsze sektory S&P (3M momentum).",
    longDescription:
      "Strategia oparta o momentum sektorowy. Każdego miesiąca kapitał alokowany jest równo w 3 sektory z najwyższym 3-miesięcznym zwrotem. Wykorzystuje fakt, że liderzy zwykle pozostają liderami przez kilka miesięcy.",
    entryRules: ["Pierwsza sesja miesiąca", "Top 3 sektory wg 3M zwrotu"],
    exitRules: ["Koniec miesiąca — rotacja", "Sektor wypada z Top 5"],
    worksWhen: "Wyraźne fazy cyklu, dyspersja między sektorami.",
    failsWhen: "Rynek bez kierunku, mean reversion sektorowy.",
    risk: "średnie",
    backtest: { winRate: 62, avgRR: 1.8, trades: 60 },
    observations: ["Lepsze wyniki w drugiej połowie cyklu wzrostowego."],
    horizon: "średni",
    instruments: ["XLK", "XLF", "XLV", "XLY", "XLC", "XLI", "XLE", "XLU", "XLP", "XLB", "XLRE"],
    parameters: [
      { name: "Okres momentum", value: "3 miesiące" },
      { name: "Liczba sektorów", value: "3" },
      { name: "Częstotliwość rotacji", value: "miesięcznie" },
    ],
    dependencies: ["Wyraźny cykl koniunkturalny", "Dyspersja sektorowa", "Brak event-driven shocków"],
    examples: [
      { date: "2024-Q1", setup: "Top: XLK, XLC, XLF", outcome: "+9.4% kw." },
      { date: "2022-Q2", setup: "Top: XLE, XLP, XLU", outcome: "+3.1% (defensywa)" },
    ],
    marketRegime: ["mid-late-cycle", "expansion"],
    capitalRequirement: "Min. 3 000 USD (3 ETF).",
    timeCommitment: "1× miesiąc, 30 min.",
    pros: ["Niskie koszty", "Działa w różnych fazach cyklu"],
    cons: ["Może podążać za trendem zbyt długo", "Wymaga dyscypliny rotacji"],
    related: ["trend-following"],
  },
  {
    id: "dividend-growth",
    name: "Dividend Growth (Aristocrats DCA)",
    description: "Comiesięczne DCA do spółek z 25+ lat wzrostu dywidendy.",
    longDescription:
      "Długoterminowa strategia kupowania spółek o stabilnej historii podnoszenia dywidendy. Generuje rosnący strumień gotówki i zwykle ma niższą zmienność niż szeroki rynek.",
    entryRules: ["Stała kwota co miesiąc", "Tylko spółki z indeksu Aristocrats"],
    exitRules: ["Cięcie dywidendy", "Dywidenda < 1.5%"],
    worksWhen: "Każde otoczenie — strategia długoterminowa.",
    failsWhen: "Krótkie horyzonty (< 5 lat), pogoń za zwrotem.",
    risk: "niskie",
    backtest: { winRate: 84, avgRR: 1.2, trades: 240 },
    observations: ["Ogranicza obsunięcia, ale kosztem upside w hossie tech."],
    horizon: "długi",
    instruments: ["NOBL", "VIG", "SCHD", "PG", "JNJ", "KO", "PEP"],
    parameters: [
      { name: "Częstotliwość", value: "co miesiąc" },
      { name: "Min. yield", value: "1.5%" },
      { name: "Min. historia wzrostu", value: "25 lat" },
    ],
    dependencies: ["Stabilność spółek", "Polityka dywidendowa", "Otoczenie podatkowe"],
    examples: [
      { date: "2020-03", setup: "Krach COVID — DCA bez przerwy", outcome: "+38% w 18 mies." },
    ],
    marketRegime: ["any"],
    capitalRequirement: "Od 100 USD/mies.",
    timeCommitment: "Praktycznie zerowy.",
    pros: ["Pasywny dochód", "Niska zmienność", "Działanie procentu składanego"],
    cons: ["Słabsze w hossie growth", "Reinwestycja kluczowa"],
    related: ["etf-dca"],
  },
  {
    id: "etf-dca",
    name: "ETF DCA na VTI/QQQ",
    description: "Comiesięczne uśrednianie ceny w szerokim rynku USA.",
    longDescription:
      "Najprostsza i statystycznie najskuteczniejsza strategia długoterminowa. Polega na regularnym kupowaniu jednostki ETF niezależnie od ceny — uśrednia ryzyko wejścia.",
    entryRules: ["1 dzień miesiąca", "Stała kwota niezależnie od ceny"],
    exitRules: ["Cel finansowy", "Zmiana planu życiowego"],
    worksWhen: "Każde otoczenie, długi horyzont.",
    failsWhen: "Próby market timingu zamiast trzymania planu.",
    risk: "niskie",
    backtest: { winRate: 78, avgRR: 1.6, trades: 360 },
    observations: ["Najprostsza i najskuteczniejsza dla większości."],
    horizon: "długi",
    instruments: ["VTI", "VOO", "QQQ", "VXUS"],
    parameters: [
      { name: "Częstotliwość", value: "miesięcznie" },
      { name: "Wielkość wpłaty", value: "stała w PLN" },
    ],
    dependencies: ["Stabilność dochodów", "Konsekwencja"],
    examples: [{ date: "2010-2024", setup: "$500/mies do VTI", outcome: "CAGR ≈ 12%" }],
    marketRegime: ["any"],
    capitalRequirement: "Od 100 USD/mies.",
    timeCommitment: "Zero — automatyzacja.",
    pros: ["Prostota", "Brak emocji", "Statystycznie pokonuje większość aktywnych"],
    cons: ["Brak kontroli timingu", "Wymaga długiego horyzontu"],
    related: ["dividend-growth"],
  },
  {
    id: "defensive-hedge",
    name: "Defensywny hedge (TLT + GLD)",
    description: "20% portfela w TLT i 10% w GLD jako stabilizator.",
    longDescription:
      "Mieszany hedge dla portfela akcyjnego. TLT (długie obligacje) zabezpiecza przed deflacyjną recesją, GLD (złoto) — przed inflacją i ryzykiem geopolitycznym.",
    entryRules: ["Kiedy VIX < 15 (tanio kupić ubezpieczenie)", "Po sygnałach ostrzegawczych makro"],
    exitRules: ["VIX > 30 — częściowa realizacja", "Powrót do equity, gdy spread korekt > 15%"],
    worksWhen: "Risk-off, panika, kryzysy bankowe.",
    failsWhen: "Stagflacja (TLT i GLD mogą się rozjechać).",
    risk: "średnie",
    backtest: { winRate: 54, avgRR: 1.9, trades: 32 },
    observations: ["TLT czuły na stopy — wymaga aktywnego zarządzania."],
    horizon: "średni",
    instruments: ["TLT", "GLD", "IEF"],
    parameters: [
      { name: "Alokacja TLT", value: "20%" },
      { name: "Alokacja GLD", value: "10%" },
      { name: "Próg VIX wejścia", value: "< 15" },
    ],
    dependencies: ["Polityka Fed", "Kurs dolara (DXY)", "Realne stopy"],
    examples: [
      { date: "2023-03", setup: "Kryzys SVB — GLD +8%, TLT +6%", outcome: "Hedge zadziałał" },
      { date: "2022-H1", setup: "Stagflacja — TLT -22%", outcome: "Hedge zawiódł" },
    ],
    marketRegime: ["risk-off", "deflation", "geo-shock"],
    capitalRequirement: "Min. 5 000 USD.",
    timeCommitment: "Tygodniowy przegląd.",
    pros: ["Dywersyfikacja", "Działa w panice"],
    cons: ["Drag w hossie", "Stagflacja go łamie"],
    related: ["trend-following"],
  },
];
