/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SqueezeRouteImport } from './routes/squeeze'
import { Route as SlownikRouteImport } from './routes/slownik'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SilaRouteImport } from './routes/sila'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupyRouteImport } from './routes/setupy'
import { Route as SentymentRouteImport } from './routes/sentyment'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as PrzeplywRouteImport } from './routes/przeplyw'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LikwidacjaRouteImport } from './routes/likwidacja'
import { Route as GieldaRouteImport } from './routes/gielda'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GieldaIndexRouteImport } from './routes/gielda.index'
import { Route as GieldaWatchlistaRouteImport } from './routes/gielda.watchlista'
import { Route as GieldaUsaRouteImport } from './routes/gielda.usa'
import { Route as GieldaTaktykiRouteImport } from './routes/gielda.taktyki'
import { Route as GieldaSektoryRouteImport } from './routes/gielda.sektory'
import { Route as GieldaMakroRouteImport } from './routes/gielda.makro'
import { Route as GieldaEuropaRouteImport } from './routes/gielda.europa'
import { Route as GieldaEtfRouteImport } from './routes/gielda.etf'
import { Route as GieldaDziennikRouteImport } from './routes/gielda.dziennik'
import { Route as GieldaBajtlikRouteImport } from './routes/gielda.bajtlik'
import { Route as GieldaAgentRouteImport } from './routes/gielda.agent'
import { Route as CoinSymbolRouteImport } from './routes/coin.$symbol'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedUstawieniaRouteImport } from './routes/_authenticated/ustawienia'
import { Route as AuthenticatedUlubioneRouteImport } from './routes/_authenticated/ulubione'
import { Route as AuthenticatedHistoriaAlertowRouteImport } from './routes/_authenticated/historia-alertow'
import { Route as AuthenticatedAsystentRouteImport } from './routes/_authenticated/asystent'
import { Route as AuthenticatedAlertyRouteImport } from './routes/_authenticated/alerty'

const SqueezeRoute = SqueezeRouteImport.update({
  id: '/squeeze',
  path: '/squeeze',
  getParentRoute: () => rootRouteImport,
} as any)
const SlownikRoute = SlownikRouteImport.update({
  id: '/slownik',
  path: '/slownik',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SilaRoute = SilaRouteImport.update({
  id: '/sila',
  path: '/sila',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupyRoute = SetupyRouteImport.update({
  id: '/setupy',
  path: '/setupy',
  getParentRoute: () => rootRouteImport,
} as any)
const SentymentRoute = SentymentRouteImport.update({
  id: '/sentyment',
  path: '/sentyment',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrzeplywRoute = PrzeplywRouteImport.update({
  id: '/przeplyw',
  path: '/przeplyw',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LikwidacjaRoute = LikwidacjaRouteImport.update({
  id: '/likwidacja',
  path: '/likwidacja',
  getParentRoute: () => rootRouteImport,
} as any)
const GieldaRoute = GieldaRouteImport.update({
  id: '/gielda',
  path: '/gielda',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GieldaIndexRoute = GieldaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaWatchlistaRoute = GieldaWatchlistaRouteImport.update({
  id: '/watchlista',
  path: '/watchlista',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaUsaRoute = GieldaUsaRouteImport.update({
  id: '/usa',
  path: '/usa',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaTaktykiRoute = GieldaTaktykiRouteImport.update({
  id: '/taktyki',
  path: '/taktyki',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaSektoryRoute = GieldaSektoryRouteImport.update({
  id: '/sektory',
  path: '/sektory',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaMakroRoute = GieldaMakroRouteImport.update({
  id: '/makro',
  path: '/makro',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaEuropaRoute = GieldaEuropaRouteImport.update({
  id: '/europa',
  path: '/europa',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaEtfRoute = GieldaEtfRouteImport.update({
  id: '/etf',
  path: '/etf',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaDziennikRoute = GieldaDziennikRouteImport.update({
  id: '/dziennik',
  path: '/dziennik',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaBajtlikRoute = GieldaBajtlikRouteImport.update({
  id: '/bajtlik',
  path: '/bajtlik',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaAgentRoute = GieldaAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => GieldaRoute,
} as any)
const CoinSymbolRoute = CoinSymbolRouteImport.update({
  id: '/coin/$symbol',
  path: '/coin/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUstawieniaRoute = AuthenticatedUstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUlubioneRoute = AuthenticatedUlubioneRouteImport.update({
  id: '/ulubione',
  path: '/ulubione',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoriaAlertowRoute =
  AuthenticatedHistoriaAlertowRouteImport.update({
    id: '/historia-alertow',
    path: '/historia-alertow',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAsystentRoute = AuthenticatedAsystentRouteImport.update({
  id: '/asystent',
  path: '/asystent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertyRoute = AuthenticatedAlertyRouteImport.update({
  id: '/alerty',
  path: '/alerty',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/gielda': typeof GieldaRouteWithChildren
  '/likwidacja': typeof LikwidacjaRoute
  '/login': typeof LoginRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/przeplyw': typeof PrzeplywRoute
  '/regulamin': typeof RegulaminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sentyment': typeof SentymentRoute
  '/setupy': typeof SetupyRoute
  '/signup': typeof SignupRoute
  '/sila': typeof SilaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slownik': typeof SlownikRoute
  '/squeeze': typeof SqueezeRoute
  '/alerty': typeof AuthenticatedAlertyRoute
  '/asystent': typeof AuthenticatedAsystentRoute
  '/historia-alertow': typeof AuthenticatedHistoriaAlertowRoute
  '/ulubione': typeof AuthenticatedUlubioneRoute
  '/ustawienia': typeof AuthenticatedUstawieniaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/coin/$symbol': typeof CoinSymbolRoute
  '/gielda/agent': typeof GieldaAgentRoute
  '/gielda/bajtlik': typeof GieldaBajtlikRoute
  '/gielda/dziennik': typeof GieldaDziennikRoute
  '/gielda/etf': typeof GieldaEtfRoute
  '/gielda/europa': typeof GieldaEuropaRoute
  '/gielda/makro': typeof GieldaMakroRoute
  '/gielda/sektory': typeof GieldaSektoryRoute
  '/gielda/taktyki': typeof GieldaTaktykiRoute
  '/gielda/usa': typeof GieldaUsaRoute
  '/gielda/watchlista': typeof GieldaWatchlistaRoute
  '/gielda/': typeof GieldaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/likwidacja': typeof LikwidacjaRoute
  '/login': typeof LoginRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/przeplyw': typeof PrzeplywRoute
  '/regulamin': typeof RegulaminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sentyment': typeof SentymentRoute
  '/setupy': typeof SetupyRoute
  '/signup': typeof SignupRoute
  '/sila': typeof SilaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slownik': typeof SlownikRoute
  '/squeeze': typeof SqueezeRoute
  '/alerty': typeof AuthenticatedAlertyRoute
  '/asystent': typeof AuthenticatedAsystentRoute
  '/historia-alertow': typeof AuthenticatedHistoriaAlertowRoute
  '/ulubione': typeof AuthenticatedUlubioneRoute
  '/ustawienia': typeof AuthenticatedUstawieniaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/coin/$symbol': typeof CoinSymbolRoute
  '/gielda/agent': typeof GieldaAgentRoute
  '/gielda/bajtlik': typeof GieldaBajtlikRoute
  '/gielda/dziennik': typeof GieldaDziennikRoute
  '/gielda/etf': typeof GieldaEtfRoute
  '/gielda/europa': typeof GieldaEuropaRoute
  '/gielda/makro': typeof GieldaMakroRoute
  '/gielda/sektory': typeof GieldaSektoryRoute
  '/gielda/taktyki': typeof GieldaTaktykiRoute
  '/gielda/usa': typeof GieldaUsaRoute
  '/gielda/watchlista': typeof GieldaWatchlistaRoute
  '/gielda': typeof GieldaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/gielda': typeof GieldaRouteWithChildren
  '/likwidacja': typeof LikwidacjaRoute
  '/login': typeof LoginRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/przeplyw': typeof PrzeplywRoute
  '/regulamin': typeof RegulaminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sentyment': typeof SentymentRoute
  '/setupy': typeof SetupyRoute
  '/signup': typeof SignupRoute
  '/sila': typeof SilaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slownik': typeof SlownikRoute
  '/squeeze': typeof SqueezeRoute
  '/_authenticated/alerty': typeof AuthenticatedAlertyRoute
  '/_authenticated/asystent': typeof AuthenticatedAsystentRoute
  '/_authenticated/historia-alertow': typeof AuthenticatedHistoriaAlertowRoute
  '/_authenticated/ulubione': typeof AuthenticatedUlubioneRoute
  '/_authenticated/ustawienia': typeof AuthenticatedUstawieniaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/coin/$symbol': typeof CoinSymbolRoute
  '/gielda/agent': typeof GieldaAgentRoute
  '/gielda/bajtlik': typeof GieldaBajtlikRoute
  '/gielda/dziennik': typeof GieldaDziennikRoute
  '/gielda/etf': typeof GieldaEtfRoute
  '/gielda/europa': typeof GieldaEuropaRoute
  '/gielda/makro': typeof GieldaMakroRoute
  '/gielda/sektory': typeof GieldaSektoryRoute
  '/gielda/taktyki': typeof GieldaTaktykiRoute
  '/gielda/usa': typeof GieldaUsaRoute
  '/gielda/watchlista': typeof GieldaWatchlistaRoute
  '/gielda/': typeof GieldaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disclaimer'
    | '/gielda'
    | '/likwidacja'
    | '/login'
    | '/polityka-prywatnosci'
    | '/przeplyw'
    | '/regulamin'
    | '/reset-password'
    | '/sentyment'
    | '/setupy'
    | '/signup'
    | '/sila'
    | '/sitemap.xml'
    | '/slownik'
    | '/squeeze'
    | '/alerty'
    | '/asystent'
    | '/historia-alertow'
    | '/ulubione'
    | '/ustawienia'
    | '/auth/callback'
    | '/coin/$symbol'
    | '/gielda/agent'
    | '/gielda/bajtlik'
    | '/gielda/dziennik'
    | '/gielda/etf'
    | '/gielda/europa'
    | '/gielda/makro'
    | '/gielda/sektory'
    | '/gielda/taktyki'
    | '/gielda/usa'
    | '/gielda/watchlista'
    | '/gielda/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disclaimer'
    | '/likwidacja'
    | '/login'
    | '/polityka-prywatnosci'
    | '/przeplyw'
    | '/regulamin'
    | '/reset-password'
    | '/sentyment'
    | '/setupy'
    | '/signup'
    | '/sila'
    | '/sitemap.xml'
    | '/slownik'
    | '/squeeze'
    | '/alerty'
    | '/asystent'
    | '/historia-alertow'
    | '/ulubione'
    | '/ustawienia'
    | '/auth/callback'
    | '/coin/$symbol'
    | '/gielda/agent'
    | '/gielda/bajtlik'
    | '/gielda/dziennik'
    | '/gielda/etf'
    | '/gielda/europa'
    | '/gielda/makro'
    | '/gielda/sektory'
    | '/gielda/taktyki'
    | '/gielda/usa'
    | '/gielda/watchlista'
    | '/gielda'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/disclaimer'
    | '/gielda'
    | '/likwidacja'
    | '/login'
    | '/polityka-prywatnosci'
    | '/przeplyw'
    | '/regulamin'
    | '/reset-password'
    | '/sentyment'
    | '/setupy'
    | '/signup'
    | '/sila'
    | '/sitemap.xml'
    | '/slownik'
    | '/squeeze'
    | '/_authenticated/alerty'
    | '/_authenticated/asystent'
    | '/_authenticated/historia-alertow'
    | '/_authenticated/ulubione'
    | '/_authenticated/ustawienia'
    | '/auth/callback'
    | '/coin/$symbol'
    | '/gielda/agent'
    | '/gielda/bajtlik'
    | '/gielda/dziennik'
    | '/gielda/etf'
    | '/gielda/europa'
    | '/gielda/makro'
    | '/gielda/sektory'
    | '/gielda/taktyki'
    | '/gielda/usa'
    | '/gielda/watchlista'
    | '/gielda/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DisclaimerRoute: typeof DisclaimerRoute
  GieldaRoute: typeof GieldaRouteWithChildren
  LikwidacjaRoute: typeof LikwidacjaRoute
  LoginRoute: typeof LoginRoute
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
  PrzeplywRoute: typeof PrzeplywRoute
  RegulaminRoute: typeof RegulaminRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SentymentRoute: typeof SentymentRoute
  SetupyRoute: typeof SetupyRoute
  SignupRoute: typeof SignupRoute
  SilaRoute: typeof SilaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlownikRoute: typeof SlownikRoute
  SqueezeRoute: typeof SqueezeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CoinSymbolRoute: typeof CoinSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/squeeze': {
      id: '/squeeze'
      path: '/squeeze'
      fullPath: '/squeeze'
      preLoaderRoute: typeof SqueezeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slownik': {
      id: '/slownik'
      path: '/slownik'
      fullPath: '/slownik'
      preLoaderRoute: typeof SlownikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sila': {
      id: '/sila'
      path: '/sila'
      fullPath: '/sila'
      preLoaderRoute: typeof SilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setupy': {
      id: '/setupy'
      path: '/setupy'
      fullPath: '/setupy'
      preLoaderRoute: typeof SetupyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentyment': {
      id: '/sentyment'
      path: '/sentyment'
      fullPath: '/sentyment'
      preLoaderRoute: typeof SentymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/przeplyw': {
      id: '/przeplyw'
      path: '/przeplyw'
      fullPath: '/przeplyw'
      preLoaderRoute: typeof PrzeplywRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/likwidacja': {
      id: '/likwidacja'
      path: '/likwidacja'
      fullPath: '/likwidacja'
      preLoaderRoute: typeof LikwidacjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gielda': {
      id: '/gielda'
      path: '/gielda'
      fullPath: '/gielda'
      preLoaderRoute: typeof GieldaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gielda/': {
      id: '/gielda/'
      path: '/'
      fullPath: '/gielda/'
      preLoaderRoute: typeof GieldaIndexRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/watchlista': {
      id: '/gielda/watchlista'
      path: '/watchlista'
      fullPath: '/gielda/watchlista'
      preLoaderRoute: typeof GieldaWatchlistaRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/usa': {
      id: '/gielda/usa'
      path: '/usa'
      fullPath: '/gielda/usa'
      preLoaderRoute: typeof GieldaUsaRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/taktyki': {
      id: '/gielda/taktyki'
      path: '/taktyki'
      fullPath: '/gielda/taktyki'
      preLoaderRoute: typeof GieldaTaktykiRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/sektory': {
      id: '/gielda/sektory'
      path: '/sektory'
      fullPath: '/gielda/sektory'
      preLoaderRoute: typeof GieldaSektoryRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/makro': {
      id: '/gielda/makro'
      path: '/makro'
      fullPath: '/gielda/makro'
      preLoaderRoute: typeof GieldaMakroRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/europa': {
      id: '/gielda/europa'
      path: '/europa'
      fullPath: '/gielda/europa'
      preLoaderRoute: typeof GieldaEuropaRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/etf': {
      id: '/gielda/etf'
      path: '/etf'
      fullPath: '/gielda/etf'
      preLoaderRoute: typeof GieldaEtfRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/dziennik': {
      id: '/gielda/dziennik'
      path: '/dziennik'
      fullPath: '/gielda/dziennik'
      preLoaderRoute: typeof GieldaDziennikRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/bajtlik': {
      id: '/gielda/bajtlik'
      path: '/bajtlik'
      fullPath: '/gielda/bajtlik'
      preLoaderRoute: typeof GieldaBajtlikRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/agent': {
      id: '/gielda/agent'
      path: '/agent'
      fullPath: '/gielda/agent'
      preLoaderRoute: typeof GieldaAgentRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/coin/$symbol': {
      id: '/coin/$symbol'
      path: '/coin/$symbol'
      fullPath: '/coin/$symbol'
      preLoaderRoute: typeof CoinSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ustawienia': {
      id: '/_authenticated/ustawienia'
      path: '/ustawienia'
      fullPath: '/ustawienia'
      preLoaderRoute: typeof AuthenticatedUstawieniaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ulubione': {
      id: '/_authenticated/ulubione'
      path: '/ulubione'
      fullPath: '/ulubione'
      preLoaderRoute: typeof AuthenticatedUlubioneRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historia-alertow': {
      id: '/_authenticated/historia-alertow'
      path: '/historia-alertow'
      fullPath: '/historia-alertow'
      preLoaderRoute: typeof AuthenticatedHistoriaAlertowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/asystent': {
      id: '/_authenticated/asystent'
      path: '/asystent'
      fullPath: '/asystent'
      preLoaderRoute: typeof AuthenticatedAsystentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerty': {
      id: '/_authenticated/alerty'
      path: '/alerty'
      fullPath: '/alerty'
      preLoaderRoute: typeof AuthenticatedAlertyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAlertyRoute: typeof AuthenticatedAlertyRoute
  AuthenticatedAsystentRoute: typeof AuthenticatedAsystentRoute
  AuthenticatedHistoriaAlertowRoute: typeof AuthenticatedHistoriaAlertowRoute
  AuthenticatedUlubioneRoute: typeof AuthenticatedUlubioneRoute
  AuthenticatedUstawieniaRoute: typeof AuthenticatedUstawieniaRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertyRoute: AuthenticatedAlertyRoute,
  AuthenticatedAsystentRoute: AuthenticatedAsystentRoute,
  AuthenticatedHistoriaAlertowRoute: AuthenticatedHistoriaAlertowRoute,
  AuthenticatedUlubioneRoute: AuthenticatedUlubioneRoute,
  AuthenticatedUstawieniaRoute: AuthenticatedUstawieniaRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GieldaRouteChildren {
  GieldaAgentRoute: typeof GieldaAgentRoute
  GieldaBajtlikRoute: typeof GieldaBajtlikRoute
  GieldaDziennikRoute: typeof GieldaDziennikRoute
  GieldaEtfRoute: typeof GieldaEtfRoute
  GieldaEuropaRoute: typeof GieldaEuropaRoute
  GieldaMakroRoute: typeof GieldaMakroRoute
  GieldaSektoryRoute: typeof GieldaSektoryRoute
  GieldaTaktykiRoute: typeof GieldaTaktykiRoute
  GieldaUsaRoute: typeof GieldaUsaRoute
  GieldaWatchlistaRoute: typeof GieldaWatchlistaRoute
  GieldaIndexRoute: typeof GieldaIndexRoute
}

const GieldaRouteChildren: GieldaRouteChildren = {
  GieldaAgentRoute: GieldaAgentRoute,
  GieldaBajtlikRoute: GieldaBajtlikRoute,
  GieldaDziennikRoute: GieldaDziennikRoute,
  GieldaEtfRoute: GieldaEtfRoute,
  GieldaEuropaRoute: GieldaEuropaRoute,
  GieldaMakroRoute: GieldaMakroRoute,
  GieldaSektoryRoute: GieldaSektoryRoute,
  GieldaTaktykiRoute: GieldaTaktykiRoute,
  GieldaUsaRoute: GieldaUsaRoute,
  GieldaWatchlistaRoute: GieldaWatchlistaRoute,
  GieldaIndexRoute: GieldaIndexRoute,
}

const GieldaRouteWithChildren =
  GieldaRoute._addFileChildren(GieldaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DisclaimerRoute: DisclaimerRoute,
  GieldaRoute: GieldaRouteWithChildren,
  LikwidacjaRoute: LikwidacjaRoute,
  LoginRoute: LoginRoute,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
  PrzeplywRoute: PrzeplywRoute,
  RegulaminRoute: RegulaminRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SentymentRoute: SentymentRoute,
  SetupyRoute: SetupyRoute,
  SignupRoute: SignupRoute,
  SilaRoute: SilaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlownikRoute: SlownikRoute,
  SqueezeRoute: SqueezeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CoinSymbolRoute: CoinSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
