/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UstawieniaRouteImport } from './routes/ustawienia'
import { Route as UlubioneRouteImport } from './routes/ulubione'
import { Route as SqueezeRouteImport } from './routes/squeeze'
import { Route as SlownikRouteImport } from './routes/slownik'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SilaRouteImport } from './routes/sila'
import { Route as SetupyRouteImport } from './routes/setupy'
import { Route as SentymentRouteImport } from './routes/sentyment'
import { Route as PrzeplywRouteImport } from './routes/przeplyw'
import { Route as LikwidacjaRouteImport } from './routes/likwidacja'
import { Route as HistoriaAlertowRouteImport } from './routes/historia-alertow'
import { Route as AsystentRouteImport } from './routes/asystent'
import { Route as AlertyRouteImport } from './routes/alerty'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoinSymbolRouteImport } from './routes/coin.$symbol'

const UstawieniaRoute = UstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => rootRouteImport,
} as any)
const UlubioneRoute = UlubioneRouteImport.update({
  id: '/ulubione',
  path: '/ulubione',
  getParentRoute: () => rootRouteImport,
} as any)
const SqueezeRoute = SqueezeRouteImport.update({
  id: '/squeeze',
  path: '/squeeze',
  getParentRoute: () => rootRouteImport,
} as any)
const SlownikRoute = SlownikRouteImport.update({
  id: '/slownik',
  path: '/slownik',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SilaRoute = SilaRouteImport.update({
  id: '/sila',
  path: '/sila',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupyRoute = SetupyRouteImport.update({
  id: '/setupy',
  path: '/setupy',
  getParentRoute: () => rootRouteImport,
} as any)
const SentymentRoute = SentymentRouteImport.update({
  id: '/sentyment',
  path: '/sentyment',
  getParentRoute: () => rootRouteImport,
} as any)
const PrzeplywRoute = PrzeplywRouteImport.update({
  id: '/przeplyw',
  path: '/przeplyw',
  getParentRoute: () => rootRouteImport,
} as any)
const LikwidacjaRoute = LikwidacjaRouteImport.update({
  id: '/likwidacja',
  path: '/likwidacja',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaAlertowRoute = HistoriaAlertowRouteImport.update({
  id: '/historia-alertow',
  path: '/historia-alertow',
  getParentRoute: () => rootRouteImport,
} as any)
const AsystentRoute = AsystentRouteImport.update({
  id: '/asystent',
  path: '/asystent',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertyRoute = AlertyRouteImport.update({
  id: '/alerty',
  path: '/alerty',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinSymbolRoute = CoinSymbolRouteImport.update({
  id: '/coin/$symbol',
  path: '/coin/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerty': typeof AlertyRoute
  '/asystent': typeof AsystentRoute
  '/historia-alertow': typeof HistoriaAlertowRoute
  '/likwidacja': typeof LikwidacjaRoute
  '/przeplyw': typeof PrzeplywRoute
  '/sentyment': typeof SentymentRoute
  '/setupy': typeof SetupyRoute
  '/sila': typeof SilaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slownik': typeof SlownikRoute
  '/squeeze': typeof SqueezeRoute
  '/ulubione': typeof UlubioneRoute
  '/ustawienia': typeof UstawieniaRoute
  '/coin/$symbol': typeof CoinSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerty': typeof AlertyRoute
  '/asystent': typeof AsystentRoute
  '/historia-alertow': typeof HistoriaAlertowRoute
  '/likwidacja': typeof LikwidacjaRoute
  '/przeplyw': typeof PrzeplywRoute
  '/sentyment': typeof SentymentRoute
  '/setupy': typeof SetupyRoute
  '/sila': typeof SilaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slownik': typeof SlownikRoute
  '/squeeze': typeof SqueezeRoute
  '/ulubione': typeof UlubioneRoute
  '/ustawienia': typeof UstawieniaRoute
  '/coin/$symbol': typeof CoinSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerty': typeof AlertyRoute
  '/asystent': typeof AsystentRoute
  '/historia-alertow': typeof HistoriaAlertowRoute
  '/likwidacja': typeof LikwidacjaRoute
  '/przeplyw': typeof PrzeplywRoute
  '/sentyment': typeof SentymentRoute
  '/setupy': typeof SetupyRoute
  '/sila': typeof SilaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slownik': typeof SlownikRoute
  '/squeeze': typeof SqueezeRoute
  '/ulubione': typeof UlubioneRoute
  '/ustawienia': typeof UstawieniaRoute
  '/coin/$symbol': typeof CoinSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerty'
    | '/asystent'
    | '/historia-alertow'
    | '/likwidacja'
    | '/przeplyw'
    | '/sentyment'
    | '/setupy'
    | '/sila'
    | '/sitemap.xml'
    | '/slownik'
    | '/squeeze'
    | '/ulubione'
    | '/ustawienia'
    | '/coin/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerty'
    | '/asystent'
    | '/historia-alertow'
    | '/likwidacja'
    | '/przeplyw'
    | '/sentyment'
    | '/setupy'
    | '/sila'
    | '/sitemap.xml'
    | '/slownik'
    | '/squeeze'
    | '/ulubione'
    | '/ustawienia'
    | '/coin/$symbol'
  id:
    | '__root__'
    | '/'
    | '/alerty'
    | '/asystent'
    | '/historia-alertow'
    | '/likwidacja'
    | '/przeplyw'
    | '/sentyment'
    | '/setupy'
    | '/sila'
    | '/sitemap.xml'
    | '/slownik'
    | '/squeeze'
    | '/ulubione'
    | '/ustawienia'
    | '/coin/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertyRoute: typeof AlertyRoute
  AsystentRoute: typeof AsystentRoute
  HistoriaAlertowRoute: typeof HistoriaAlertowRoute
  LikwidacjaRoute: typeof LikwidacjaRoute
  PrzeplywRoute: typeof PrzeplywRoute
  SentymentRoute: typeof SentymentRoute
  SetupyRoute: typeof SetupyRoute
  SilaRoute: typeof SilaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlownikRoute: typeof SlownikRoute
  SqueezeRoute: typeof SqueezeRoute
  UlubioneRoute: typeof UlubioneRoute
  UstawieniaRoute: typeof UstawieniaRoute
  CoinSymbolRoute: typeof CoinSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ustawienia': {
      id: '/ustawienia'
      path: '/ustawienia'
      fullPath: '/ustawienia'
      preLoaderRoute: typeof UstawieniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ulubione': {
      id: '/ulubione'
      path: '/ulubione'
      fullPath: '/ulubione'
      preLoaderRoute: typeof UlubioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squeeze': {
      id: '/squeeze'
      path: '/squeeze'
      fullPath: '/squeeze'
      preLoaderRoute: typeof SqueezeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slownik': {
      id: '/slownik'
      path: '/slownik'
      fullPath: '/slownik'
      preLoaderRoute: typeof SlownikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sila': {
      id: '/sila'
      path: '/sila'
      fullPath: '/sila'
      preLoaderRoute: typeof SilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setupy': {
      id: '/setupy'
      path: '/setupy'
      fullPath: '/setupy'
      preLoaderRoute: typeof SetupyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentyment': {
      id: '/sentyment'
      path: '/sentyment'
      fullPath: '/sentyment'
      preLoaderRoute: typeof SentymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/przeplyw': {
      id: '/przeplyw'
      path: '/przeplyw'
      fullPath: '/przeplyw'
      preLoaderRoute: typeof PrzeplywRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/likwidacja': {
      id: '/likwidacja'
      path: '/likwidacja'
      fullPath: '/likwidacja'
      preLoaderRoute: typeof LikwidacjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia-alertow': {
      id: '/historia-alertow'
      path: '/historia-alertow'
      fullPath: '/historia-alertow'
      preLoaderRoute: typeof HistoriaAlertowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asystent': {
      id: '/asystent'
      path: '/asystent'
      fullPath: '/asystent'
      preLoaderRoute: typeof AsystentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerty': {
      id: '/alerty'
      path: '/alerty'
      fullPath: '/alerty'
      preLoaderRoute: typeof AlertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coin/$symbol': {
      id: '/coin/$symbol'
      path: '/coin/$symbol'
      fullPath: '/coin/$symbol'
      preLoaderRoute: typeof CoinSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertyRoute: AlertyRoute,
  AsystentRoute: AsystentRoute,
  HistoriaAlertowRoute: HistoriaAlertowRoute,
  LikwidacjaRoute: LikwidacjaRoute,
  PrzeplywRoute: PrzeplywRoute,
  SentymentRoute: SentymentRoute,
  SetupyRoute: SetupyRoute,
  SilaRoute: SilaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlownikRoute: SlownikRoute,
  SqueezeRoute: SqueezeRoute,
  UlubioneRoute: UlubioneRoute,
  UstawieniaRoute: UstawieniaRoute,
  CoinSymbolRoute: CoinSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
