/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SqueezeRouteImport } from './routes/squeeze'
import { Route as SlownikRouteImport } from './routes/slownik'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SilaRouteImport } from './routes/sila'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupyRouteImport } from './routes/setupy'
import { Route as SentymentRouteImport } from './routes/sentyment'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as PrzeplywRouteImport } from './routes/przeplyw'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LikwidacjaRouteImport } from './routes/likwidacja'
import { Route as LabRouteImport } from './routes/lab'
import { Route as GieldaRouteImport } from './routes/gielda'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabIndexRouteImport } from './routes/lab.index'
import { Route as GieldaIndexRouteImport } from './routes/gielda.index'
import { Route as SetupyHistoriaRouteImport } from './routes/setupy.historia'
import { Route as LabTelegramRouteImport } from './routes/lab.telegram'
import { Route as LabScannerRouteImport } from './routes/lab.scanner'
import { Route as LabRiskRouteImport } from './routes/lab.risk'
import { Route as LabRaportyRouteImport } from './routes/lab.raporty'
import { Route as LabPaperRouteImport } from './routes/lab.paper'
import { Route as LabMorningRouteImport } from './routes/lab.morning'
import { Route as LabLedgerRouteImport } from './routes/lab.ledger'
import { Route as LabJournalRouteImport } from './routes/lab.journal'
import { Route as LabEveningRouteImport } from './routes/lab.evening'
import { Route as LabBacktestRouteImport } from './routes/lab.backtest'
import { Route as GieldaWatchlistaRouteImport } from './routes/gielda.watchlista'
import { Route as GieldaUsaRouteImport } from './routes/gielda.usa'
import { Route as GieldaTaktykiRouteImport } from './routes/gielda.taktyki'
import { Route as GieldaSektoryRouteImport } from './routes/gielda.sektory'
import { Route as GieldaMakroRouteImport } from './routes/gielda.makro'
import { Route as GieldaEuropaRouteImport } from './routes/gielda.europa'
import { Route as GieldaEtfRouteImport } from './routes/gielda.etf'
import { Route as GieldaDziennikRouteImport } from './routes/gielda.dziennik'
import { Route as GieldaBajtlikRouteImport } from './routes/gielda.bajtlik'
import { Route as GieldaAgentRouteImport } from './routes/gielda.agent'
import { Route as CoinSymbolRouteImport } from './routes/coin.$symbol'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedUstawieniaRouteImport } from './routes/_authenticated/ustawienia'
import { Route as AuthenticatedUlubioneRouteImport } from './routes/_authenticated/ulubione'
import { Route as AuthenticatedKsiegaRouteImport } from './routes/_authenticated/ksiega'
import { Route as AuthenticatedHistoriaAlertowRouteImport } from './routes/_authenticated/historia-alertow'
import { Route as AuthenticatedAsystentRouteImport } from './routes/_authenticated/asystent'
import { Route as AuthenticatedAlertyRouteImport } from './routes/_authenticated/alerty'
import { Route as ApiPublicHooksVerifySetupsRouteImport } from './routes/api/public/hooks/verify-setups'
import { Route as ApiPublicHooksScanSetupsRouteImport } from './routes/api/public/hooks/scan-setups'
import { Route as ApiPublicHooksNotifySetupsRouteImport } from './routes/api/public/hooks/notify-setups'
import { Route as ApiPublicHooksLabReportsRouteImport } from './routes/api/public/hooks/lab-reports'
import { Route as ApiPublicHooksAgentSimulationTickRouteImport } from './routes/api/public/hooks/agent-simulation-tick'

const SqueezeRoute = SqueezeRouteImport.update({
  id: '/squeeze',
  path: '/squeeze',
  getParentRoute: () => rootRouteImport,
} as any)
const SlownikRoute = SlownikRouteImport.update({
  id: '/slownik',
  path: '/slownik',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SilaRoute = SilaRouteImport.update({
  id: '/sila',
  path: '/sila',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupyRoute = SetupyRouteImport.update({
  id: '/setupy',
  path: '/setupy',
  getParentRoute: () => rootRouteImport,
} as any)
const SentymentRoute = SentymentRouteImport.update({
  id: '/sentyment',
  path: '/sentyment',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrzeplywRoute = PrzeplywRouteImport.update({
  id: '/przeplyw',
  path: '/przeplyw',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LikwidacjaRoute = LikwidacjaRouteImport.update({
  id: '/likwidacja',
  path: '/likwidacja',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const GieldaRoute = GieldaRouteImport.update({
  id: '/gielda',
  path: '/gielda',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabRoute,
} as any)
const GieldaIndexRoute = GieldaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GieldaRoute,
} as any)
const SetupyHistoriaRoute = SetupyHistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => SetupyRoute,
} as any)
const LabTelegramRoute = LabTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => LabRoute,
} as any)
const LabScannerRoute = LabScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => LabRoute,
} as any)
const LabRiskRoute = LabRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => LabRoute,
} as any)
const LabRaportyRoute = LabRaportyRouteImport.update({
  id: '/raporty',
  path: '/raporty',
  getParentRoute: () => LabRoute,
} as any)
const LabPaperRoute = LabPaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => LabRoute,
} as any)
const LabMorningRoute = LabMorningRouteImport.update({
  id: '/morning',
  path: '/morning',
  getParentRoute: () => LabRoute,
} as any)
const LabLedgerRoute = LabLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => LabRoute,
} as any)
const LabJournalRoute = LabJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => LabRoute,
} as any)
const LabEveningRoute = LabEveningRouteImport.update({
  id: '/evening',
  path: '/evening',
  getParentRoute: () => LabRoute,
} as any)
const LabBacktestRoute = LabBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => LabRoute,
} as any)
const GieldaWatchlistaRoute = GieldaWatchlistaRouteImport.update({
  id: '/watchlista',
  path: '/watchlista',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaUsaRoute = GieldaUsaRouteImport.update({
  id: '/usa',
  path: '/usa',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaTaktykiRoute = GieldaTaktykiRouteImport.update({
  id: '/taktyki',
  path: '/taktyki',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaSektoryRoute = GieldaSektoryRouteImport.update({
  id: '/sektory',
  path: '/sektory',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaMakroRoute = GieldaMakroRouteImport.update({
  id: '/makro',
  path: '/makro',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaEuropaRoute = GieldaEuropaRouteImport.update({
  id: '/europa',
  path: '/europa',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaEtfRoute = GieldaEtfRouteImport.update({
  id: '/etf',
  path: '/etf',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaDziennikRoute = GieldaDziennikRouteImport.update({
  id: '/dziennik',
  path: '/dziennik',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaBajtlikRoute = GieldaBajtlikRouteImport.update({
  id: '/bajtlik',
  path: '/bajtlik',
  getParentRoute: () => GieldaRoute,
} as any)
const GieldaAgentRoute = GieldaAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => GieldaRoute,
} as any)
const CoinSymbolRoute = CoinSymbolRouteImport.update({
  id: '/coin/$symbol',
  path: '/coin/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUstawieniaRoute = AuthenticatedUstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUlubioneRoute = AuthenticatedUlubioneRouteImport.update({
  id: '/ulubione',
  path: '/ulubione',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKsiegaRoute = AuthenticatedKsiegaRouteImport.update({
  id: '/ksiega',
  path: '/ksiega',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoriaAlertowRoute =
  AuthenticatedHistoriaAlertowRouteImport.update({
    id: '/historia-alertow',
    path: '/historia-alertow',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAsystentRoute = AuthenticatedAsystentRouteImport.update({
  id: '/asystent',
  path: '/asystent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertyRoute = AuthenticatedAlertyRouteImport.update({
  id: '/alerty',
  path: '/alerty',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHooksVerifySetupsRoute =
  ApiPublicHooksVerifySetupsRouteImport.update({
    id: '/api/public/hooks/verify-setups',
    path: '/api/public/hooks/verify-setups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScanSetupsRoute =
  ApiPublicHooksScanSetupsRouteImport.update({
    id: '/api/public/hooks/scan-setups',
    path: '/api/public/hooks/scan-setups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotifySetupsRoute =
  ApiPublicHooksNotifySetupsRouteImport.update({
    id: '/api/public/hooks/notify-setups',
    path: '/api/public/hooks/notify-setups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLabReportsRoute =
  ApiPublicHooksLabReportsRouteImport.update({
    id: '/api/public/hooks/lab-reports',
    path: '/api/public/hooks/lab-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgentSimulationTickRoute =
  ApiPublicHooksAgentSimulationTickRouteImport.update({
    id: '/api/public/hooks/agent-simulation-tick',
    path: '/api/public/hooks/agent-simulation-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/disclaimer': typeof DisclaimerRoute
  '/gielda': typeof GieldaRouteWithChildren
  '/lab': typeof LabRouteWithChildren
  '/likwidacja': typeof LikwidacjaRoute
  '/login': typeof LoginRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/przeplyw': typeof PrzeplywRoute
  '/regulamin': typeof RegulaminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sentyment': typeof SentymentRoute
  '/setupy': typeof SetupyRouteWithChildren
  '/signup': typeof SignupRoute
  '/sila': typeof SilaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slownik': typeof SlownikRoute
  '/squeeze': typeof SqueezeRoute
  '/alerty': typeof AuthenticatedAlertyRoute
  '/asystent': typeof AuthenticatedAsystentRoute
  '/historia-alertow': typeof AuthenticatedHistoriaAlertowRoute
  '/ksiega': typeof AuthenticatedKsiegaRoute
  '/ulubione': typeof AuthenticatedUlubioneRoute
  '/ustawienia': typeof AuthenticatedUstawieniaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/coin/$symbol': typeof CoinSymbolRoute
  '/gielda/agent': typeof GieldaAgentRoute
  '/gielda/bajtlik': typeof GieldaBajtlikRoute
  '/gielda/dziennik': typeof GieldaDziennikRoute
  '/gielda/etf': typeof GieldaEtfRoute
  '/gielda/europa': typeof GieldaEuropaRoute
  '/gielda/makro': typeof GieldaMakroRoute
  '/gielda/sektory': typeof GieldaSektoryRoute
  '/gielda/taktyki': typeof GieldaTaktykiRoute
  '/gielda/usa': typeof GieldaUsaRoute
  '/gielda/watchlista': typeof GieldaWatchlistaRoute
  '/lab/backtest': typeof LabBacktestRoute
  '/lab/evening': typeof LabEveningRoute
  '/lab/journal': typeof LabJournalRoute
  '/lab/ledger': typeof LabLedgerRoute
  '/lab/morning': typeof LabMorningRoute
  '/lab/paper': typeof LabPaperRoute
  '/lab/raporty': typeof LabRaportyRoute
  '/lab/risk': typeof LabRiskRoute
  '/lab/scanner': typeof LabScannerRoute
  '/lab/telegram': typeof LabTelegramRoute
  '/setupy/historia': typeof SetupyHistoriaRoute
  '/gielda/': typeof GieldaIndexRoute
  '/lab/': typeof LabIndexRoute
  '/api/public/hooks/agent-simulation-tick': typeof ApiPublicHooksAgentSimulationTickRoute
  '/api/public/hooks/lab-reports': typeof ApiPublicHooksLabReportsRoute
  '/api/public/hooks/notify-setups': typeof ApiPublicHooksNotifySetupsRoute
  '/api/public/hooks/scan-setups': typeof ApiPublicHooksScanSetupsRoute
  '/api/public/hooks/verify-setups': typeof ApiPublicHooksVerifySetupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/disclaimer': typeof DisclaimerRoute
  '/likwidacja': typeof LikwidacjaRoute
  '/login': typeof LoginRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/przeplyw': typeof PrzeplywRoute
  '/regulamin': typeof RegulaminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sentyment': typeof SentymentRoute
  '/setupy': typeof SetupyRouteWithChildren
  '/signup': typeof SignupRoute
  '/sila': typeof SilaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slownik': typeof SlownikRoute
  '/squeeze': typeof SqueezeRoute
  '/alerty': typeof AuthenticatedAlertyRoute
  '/asystent': typeof AuthenticatedAsystentRoute
  '/historia-alertow': typeof AuthenticatedHistoriaAlertowRoute
  '/ksiega': typeof AuthenticatedKsiegaRoute
  '/ulubione': typeof AuthenticatedUlubioneRoute
  '/ustawienia': typeof AuthenticatedUstawieniaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/coin/$symbol': typeof CoinSymbolRoute
  '/gielda/agent': typeof GieldaAgentRoute
  '/gielda/bajtlik': typeof GieldaBajtlikRoute
  '/gielda/dziennik': typeof GieldaDziennikRoute
  '/gielda/etf': typeof GieldaEtfRoute
  '/gielda/europa': typeof GieldaEuropaRoute
  '/gielda/makro': typeof GieldaMakroRoute
  '/gielda/sektory': typeof GieldaSektoryRoute
  '/gielda/taktyki': typeof GieldaTaktykiRoute
  '/gielda/usa': typeof GieldaUsaRoute
  '/gielda/watchlista': typeof GieldaWatchlistaRoute
  '/lab/backtest': typeof LabBacktestRoute
  '/lab/evening': typeof LabEveningRoute
  '/lab/journal': typeof LabJournalRoute
  '/lab/ledger': typeof LabLedgerRoute
  '/lab/morning': typeof LabMorningRoute
  '/lab/paper': typeof LabPaperRoute
  '/lab/raporty': typeof LabRaportyRoute
  '/lab/risk': typeof LabRiskRoute
  '/lab/scanner': typeof LabScannerRoute
  '/lab/telegram': typeof LabTelegramRoute
  '/setupy/historia': typeof SetupyHistoriaRoute
  '/gielda': typeof GieldaIndexRoute
  '/lab': typeof LabIndexRoute
  '/api/public/hooks/agent-simulation-tick': typeof ApiPublicHooksAgentSimulationTickRoute
  '/api/public/hooks/lab-reports': typeof ApiPublicHooksLabReportsRoute
  '/api/public/hooks/notify-setups': typeof ApiPublicHooksNotifySetupsRoute
  '/api/public/hooks/scan-setups': typeof ApiPublicHooksScanSetupsRoute
  '/api/public/hooks/verify-setups': typeof ApiPublicHooksVerifySetupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/disclaimer': typeof DisclaimerRoute
  '/gielda': typeof GieldaRouteWithChildren
  '/lab': typeof LabRouteWithChildren
  '/likwidacja': typeof LikwidacjaRoute
  '/login': typeof LoginRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/przeplyw': typeof PrzeplywRoute
  '/regulamin': typeof RegulaminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sentyment': typeof SentymentRoute
  '/setupy': typeof SetupyRouteWithChildren
  '/signup': typeof SignupRoute
  '/sila': typeof SilaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slownik': typeof SlownikRoute
  '/squeeze': typeof SqueezeRoute
  '/_authenticated/alerty': typeof AuthenticatedAlertyRoute
  '/_authenticated/asystent': typeof AuthenticatedAsystentRoute
  '/_authenticated/historia-alertow': typeof AuthenticatedHistoriaAlertowRoute
  '/_authenticated/ksiega': typeof AuthenticatedKsiegaRoute
  '/_authenticated/ulubione': typeof AuthenticatedUlubioneRoute
  '/_authenticated/ustawienia': typeof AuthenticatedUstawieniaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/coin/$symbol': typeof CoinSymbolRoute
  '/gielda/agent': typeof GieldaAgentRoute
  '/gielda/bajtlik': typeof GieldaBajtlikRoute
  '/gielda/dziennik': typeof GieldaDziennikRoute
  '/gielda/etf': typeof GieldaEtfRoute
  '/gielda/europa': typeof GieldaEuropaRoute
  '/gielda/makro': typeof GieldaMakroRoute
  '/gielda/sektory': typeof GieldaSektoryRoute
  '/gielda/taktyki': typeof GieldaTaktykiRoute
  '/gielda/usa': typeof GieldaUsaRoute
  '/gielda/watchlista': typeof GieldaWatchlistaRoute
  '/lab/backtest': typeof LabBacktestRoute
  '/lab/evening': typeof LabEveningRoute
  '/lab/journal': typeof LabJournalRoute
  '/lab/ledger': typeof LabLedgerRoute
  '/lab/morning': typeof LabMorningRoute
  '/lab/paper': typeof LabPaperRoute
  '/lab/raporty': typeof LabRaportyRoute
  '/lab/risk': typeof LabRiskRoute
  '/lab/scanner': typeof LabScannerRoute
  '/lab/telegram': typeof LabTelegramRoute
  '/setupy/historia': typeof SetupyHistoriaRoute
  '/gielda/': typeof GieldaIndexRoute
  '/lab/': typeof LabIndexRoute
  '/api/public/hooks/agent-simulation-tick': typeof ApiPublicHooksAgentSimulationTickRoute
  '/api/public/hooks/lab-reports': typeof ApiPublicHooksLabReportsRoute
  '/api/public/hooks/notify-setups': typeof ApiPublicHooksNotifySetupsRoute
  '/api/public/hooks/scan-setups': typeof ApiPublicHooksScanSetupsRoute
  '/api/public/hooks/verify-setups': typeof ApiPublicHooksVerifySetupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/disclaimer'
    | '/gielda'
    | '/lab'
    | '/likwidacja'
    | '/login'
    | '/polityka-prywatnosci'
    | '/przeplyw'
    | '/regulamin'
    | '/reset-password'
    | '/sentyment'
    | '/setupy'
    | '/signup'
    | '/sila'
    | '/sitemap.xml'
    | '/slownik'
    | '/squeeze'
    | '/alerty'
    | '/asystent'
    | '/historia-alertow'
    | '/ksiega'
    | '/ulubione'
    | '/ustawienia'
    | '/auth/callback'
    | '/coin/$symbol'
    | '/gielda/agent'
    | '/gielda/bajtlik'
    | '/gielda/dziennik'
    | '/gielda/etf'
    | '/gielda/europa'
    | '/gielda/makro'
    | '/gielda/sektory'
    | '/gielda/taktyki'
    | '/gielda/usa'
    | '/gielda/watchlista'
    | '/lab/backtest'
    | '/lab/evening'
    | '/lab/journal'
    | '/lab/ledger'
    | '/lab/morning'
    | '/lab/paper'
    | '/lab/raporty'
    | '/lab/risk'
    | '/lab/scanner'
    | '/lab/telegram'
    | '/setupy/historia'
    | '/gielda/'
    | '/lab/'
    | '/api/public/hooks/agent-simulation-tick'
    | '/api/public/hooks/lab-reports'
    | '/api/public/hooks/notify-setups'
    | '/api/public/hooks/scan-setups'
    | '/api/public/hooks/verify-setups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/disclaimer'
    | '/likwidacja'
    | '/login'
    | '/polityka-prywatnosci'
    | '/przeplyw'
    | '/regulamin'
    | '/reset-password'
    | '/sentyment'
    | '/setupy'
    | '/signup'
    | '/sila'
    | '/sitemap.xml'
    | '/slownik'
    | '/squeeze'
    | '/alerty'
    | '/asystent'
    | '/historia-alertow'
    | '/ksiega'
    | '/ulubione'
    | '/ustawienia'
    | '/auth/callback'
    | '/coin/$symbol'
    | '/gielda/agent'
    | '/gielda/bajtlik'
    | '/gielda/dziennik'
    | '/gielda/etf'
    | '/gielda/europa'
    | '/gielda/makro'
    | '/gielda/sektory'
    | '/gielda/taktyki'
    | '/gielda/usa'
    | '/gielda/watchlista'
    | '/lab/backtest'
    | '/lab/evening'
    | '/lab/journal'
    | '/lab/ledger'
    | '/lab/morning'
    | '/lab/paper'
    | '/lab/raporty'
    | '/lab/risk'
    | '/lab/scanner'
    | '/lab/telegram'
    | '/setupy/historia'
    | '/gielda'
    | '/lab'
    | '/api/public/hooks/agent-simulation-tick'
    | '/api/public/hooks/lab-reports'
    | '/api/public/hooks/notify-setups'
    | '/api/public/hooks/scan-setups'
    | '/api/public/hooks/verify-setups'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/disclaimer'
    | '/gielda'
    | '/lab'
    | '/likwidacja'
    | '/login'
    | '/polityka-prywatnosci'
    | '/przeplyw'
    | '/regulamin'
    | '/reset-password'
    | '/sentyment'
    | '/setupy'
    | '/signup'
    | '/sila'
    | '/sitemap.xml'
    | '/slownik'
    | '/squeeze'
    | '/_authenticated/alerty'
    | '/_authenticated/asystent'
    | '/_authenticated/historia-alertow'
    | '/_authenticated/ksiega'
    | '/_authenticated/ulubione'
    | '/_authenticated/ustawienia'
    | '/auth/callback'
    | '/coin/$symbol'
    | '/gielda/agent'
    | '/gielda/bajtlik'
    | '/gielda/dziennik'
    | '/gielda/etf'
    | '/gielda/europa'
    | '/gielda/makro'
    | '/gielda/sektory'
    | '/gielda/taktyki'
    | '/gielda/usa'
    | '/gielda/watchlista'
    | '/lab/backtest'
    | '/lab/evening'
    | '/lab/journal'
    | '/lab/ledger'
    | '/lab/morning'
    | '/lab/paper'
    | '/lab/raporty'
    | '/lab/risk'
    | '/lab/scanner'
    | '/lab/telegram'
    | '/setupy/historia'
    | '/gielda/'
    | '/lab/'
    | '/api/public/hooks/agent-simulation-tick'
    | '/api/public/hooks/lab-reports'
    | '/api/public/hooks/notify-setups'
    | '/api/public/hooks/scan-setups'
    | '/api/public/hooks/verify-setups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  DisclaimerRoute: typeof DisclaimerRoute
  GieldaRoute: typeof GieldaRouteWithChildren
  LabRoute: typeof LabRouteWithChildren
  LikwidacjaRoute: typeof LikwidacjaRoute
  LoginRoute: typeof LoginRoute
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
  PrzeplywRoute: typeof PrzeplywRoute
  RegulaminRoute: typeof RegulaminRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SentymentRoute: typeof SentymentRoute
  SetupyRoute: typeof SetupyRouteWithChildren
  SignupRoute: typeof SignupRoute
  SilaRoute: typeof SilaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlownikRoute: typeof SlownikRoute
  SqueezeRoute: typeof SqueezeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CoinSymbolRoute: typeof CoinSymbolRoute
  ApiPublicHooksAgentSimulationTickRoute: typeof ApiPublicHooksAgentSimulationTickRoute
  ApiPublicHooksLabReportsRoute: typeof ApiPublicHooksLabReportsRoute
  ApiPublicHooksNotifySetupsRoute: typeof ApiPublicHooksNotifySetupsRoute
  ApiPublicHooksScanSetupsRoute: typeof ApiPublicHooksScanSetupsRoute
  ApiPublicHooksVerifySetupsRoute: typeof ApiPublicHooksVerifySetupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/squeeze': {
      id: '/squeeze'
      path: '/squeeze'
      fullPath: '/squeeze'
      preLoaderRoute: typeof SqueezeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slownik': {
      id: '/slownik'
      path: '/slownik'
      fullPath: '/slownik'
      preLoaderRoute: typeof SlownikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sila': {
      id: '/sila'
      path: '/sila'
      fullPath: '/sila'
      preLoaderRoute: typeof SilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setupy': {
      id: '/setupy'
      path: '/setupy'
      fullPath: '/setupy'
      preLoaderRoute: typeof SetupyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentyment': {
      id: '/sentyment'
      path: '/sentyment'
      fullPath: '/sentyment'
      preLoaderRoute: typeof SentymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/przeplyw': {
      id: '/przeplyw'
      path: '/przeplyw'
      fullPath: '/przeplyw'
      preLoaderRoute: typeof PrzeplywRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/likwidacja': {
      id: '/likwidacja'
      path: '/likwidacja'
      fullPath: '/likwidacja'
      preLoaderRoute: typeof LikwidacjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gielda': {
      id: '/gielda'
      path: '/gielda'
      fullPath: '/gielda'
      preLoaderRoute: typeof GieldaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/gielda/': {
      id: '/gielda/'
      path: '/'
      fullPath: '/gielda/'
      preLoaderRoute: typeof GieldaIndexRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/setupy/historia': {
      id: '/setupy/historia'
      path: '/historia'
      fullPath: '/setupy/historia'
      preLoaderRoute: typeof SetupyHistoriaRouteImport
      parentRoute: typeof SetupyRoute
    }
    '/lab/telegram': {
      id: '/lab/telegram'
      path: '/telegram'
      fullPath: '/lab/telegram'
      preLoaderRoute: typeof LabTelegramRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/scanner': {
      id: '/lab/scanner'
      path: '/scanner'
      fullPath: '/lab/scanner'
      preLoaderRoute: typeof LabScannerRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/risk': {
      id: '/lab/risk'
      path: '/risk'
      fullPath: '/lab/risk'
      preLoaderRoute: typeof LabRiskRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/raporty': {
      id: '/lab/raporty'
      path: '/raporty'
      fullPath: '/lab/raporty'
      preLoaderRoute: typeof LabRaportyRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/paper': {
      id: '/lab/paper'
      path: '/paper'
      fullPath: '/lab/paper'
      preLoaderRoute: typeof LabPaperRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/morning': {
      id: '/lab/morning'
      path: '/morning'
      fullPath: '/lab/morning'
      preLoaderRoute: typeof LabMorningRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/ledger': {
      id: '/lab/ledger'
      path: '/ledger'
      fullPath: '/lab/ledger'
      preLoaderRoute: typeof LabLedgerRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/journal': {
      id: '/lab/journal'
      path: '/journal'
      fullPath: '/lab/journal'
      preLoaderRoute: typeof LabJournalRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/evening': {
      id: '/lab/evening'
      path: '/evening'
      fullPath: '/lab/evening'
      preLoaderRoute: typeof LabEveningRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/backtest': {
      id: '/lab/backtest'
      path: '/backtest'
      fullPath: '/lab/backtest'
      preLoaderRoute: typeof LabBacktestRouteImport
      parentRoute: typeof LabRoute
    }
    '/gielda/watchlista': {
      id: '/gielda/watchlista'
      path: '/watchlista'
      fullPath: '/gielda/watchlista'
      preLoaderRoute: typeof GieldaWatchlistaRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/usa': {
      id: '/gielda/usa'
      path: '/usa'
      fullPath: '/gielda/usa'
      preLoaderRoute: typeof GieldaUsaRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/taktyki': {
      id: '/gielda/taktyki'
      path: '/taktyki'
      fullPath: '/gielda/taktyki'
      preLoaderRoute: typeof GieldaTaktykiRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/sektory': {
      id: '/gielda/sektory'
      path: '/sektory'
      fullPath: '/gielda/sektory'
      preLoaderRoute: typeof GieldaSektoryRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/makro': {
      id: '/gielda/makro'
      path: '/makro'
      fullPath: '/gielda/makro'
      preLoaderRoute: typeof GieldaMakroRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/europa': {
      id: '/gielda/europa'
      path: '/europa'
      fullPath: '/gielda/europa'
      preLoaderRoute: typeof GieldaEuropaRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/etf': {
      id: '/gielda/etf'
      path: '/etf'
      fullPath: '/gielda/etf'
      preLoaderRoute: typeof GieldaEtfRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/dziennik': {
      id: '/gielda/dziennik'
      path: '/dziennik'
      fullPath: '/gielda/dziennik'
      preLoaderRoute: typeof GieldaDziennikRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/bajtlik': {
      id: '/gielda/bajtlik'
      path: '/bajtlik'
      fullPath: '/gielda/bajtlik'
      preLoaderRoute: typeof GieldaBajtlikRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/gielda/agent': {
      id: '/gielda/agent'
      path: '/agent'
      fullPath: '/gielda/agent'
      preLoaderRoute: typeof GieldaAgentRouteImport
      parentRoute: typeof GieldaRoute
    }
    '/coin/$symbol': {
      id: '/coin/$symbol'
      path: '/coin/$symbol'
      fullPath: '/coin/$symbol'
      preLoaderRoute: typeof CoinSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ustawienia': {
      id: '/_authenticated/ustawienia'
      path: '/ustawienia'
      fullPath: '/ustawienia'
      preLoaderRoute: typeof AuthenticatedUstawieniaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ulubione': {
      id: '/_authenticated/ulubione'
      path: '/ulubione'
      fullPath: '/ulubione'
      preLoaderRoute: typeof AuthenticatedUlubioneRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ksiega': {
      id: '/_authenticated/ksiega'
      path: '/ksiega'
      fullPath: '/ksiega'
      preLoaderRoute: typeof AuthenticatedKsiegaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historia-alertow': {
      id: '/_authenticated/historia-alertow'
      path: '/historia-alertow'
      fullPath: '/historia-alertow'
      preLoaderRoute: typeof AuthenticatedHistoriaAlertowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/asystent': {
      id: '/_authenticated/asystent'
      path: '/asystent'
      fullPath: '/asystent'
      preLoaderRoute: typeof AuthenticatedAsystentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerty': {
      id: '/_authenticated/alerty'
      path: '/alerty'
      fullPath: '/alerty'
      preLoaderRoute: typeof AuthenticatedAlertyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/verify-setups': {
      id: '/api/public/hooks/verify-setups'
      path: '/api/public/hooks/verify-setups'
      fullPath: '/api/public/hooks/verify-setups'
      preLoaderRoute: typeof ApiPublicHooksVerifySetupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan-setups': {
      id: '/api/public/hooks/scan-setups'
      path: '/api/public/hooks/scan-setups'
      fullPath: '/api/public/hooks/scan-setups'
      preLoaderRoute: typeof ApiPublicHooksScanSetupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notify-setups': {
      id: '/api/public/hooks/notify-setups'
      path: '/api/public/hooks/notify-setups'
      fullPath: '/api/public/hooks/notify-setups'
      preLoaderRoute: typeof ApiPublicHooksNotifySetupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lab-reports': {
      id: '/api/public/hooks/lab-reports'
      path: '/api/public/hooks/lab-reports'
      fullPath: '/api/public/hooks/lab-reports'
      preLoaderRoute: typeof ApiPublicHooksLabReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agent-simulation-tick': {
      id: '/api/public/hooks/agent-simulation-tick'
      path: '/api/public/hooks/agent-simulation-tick'
      fullPath: '/api/public/hooks/agent-simulation-tick'
      preLoaderRoute: typeof ApiPublicHooksAgentSimulationTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAlertyRoute: typeof AuthenticatedAlertyRoute
  AuthenticatedAsystentRoute: typeof AuthenticatedAsystentRoute
  AuthenticatedHistoriaAlertowRoute: typeof AuthenticatedHistoriaAlertowRoute
  AuthenticatedKsiegaRoute: typeof AuthenticatedKsiegaRoute
  AuthenticatedUlubioneRoute: typeof AuthenticatedUlubioneRoute
  AuthenticatedUstawieniaRoute: typeof AuthenticatedUstawieniaRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertyRoute: AuthenticatedAlertyRoute,
  AuthenticatedAsystentRoute: AuthenticatedAsystentRoute,
  AuthenticatedHistoriaAlertowRoute: AuthenticatedHistoriaAlertowRoute,
  AuthenticatedKsiegaRoute: AuthenticatedKsiegaRoute,
  AuthenticatedUlubioneRoute: AuthenticatedUlubioneRoute,
  AuthenticatedUstawieniaRoute: AuthenticatedUstawieniaRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GieldaRouteChildren {
  GieldaAgentRoute: typeof GieldaAgentRoute
  GieldaBajtlikRoute: typeof GieldaBajtlikRoute
  GieldaDziennikRoute: typeof GieldaDziennikRoute
  GieldaEtfRoute: typeof GieldaEtfRoute
  GieldaEuropaRoute: typeof GieldaEuropaRoute
  GieldaMakroRoute: typeof GieldaMakroRoute
  GieldaSektoryRoute: typeof GieldaSektoryRoute
  GieldaTaktykiRoute: typeof GieldaTaktykiRoute
  GieldaUsaRoute: typeof GieldaUsaRoute
  GieldaWatchlistaRoute: typeof GieldaWatchlistaRoute
  GieldaIndexRoute: typeof GieldaIndexRoute
}

const GieldaRouteChildren: GieldaRouteChildren = {
  GieldaAgentRoute: GieldaAgentRoute,
  GieldaBajtlikRoute: GieldaBajtlikRoute,
  GieldaDziennikRoute: GieldaDziennikRoute,
  GieldaEtfRoute: GieldaEtfRoute,
  GieldaEuropaRoute: GieldaEuropaRoute,
  GieldaMakroRoute: GieldaMakroRoute,
  GieldaSektoryRoute: GieldaSektoryRoute,
  GieldaTaktykiRoute: GieldaTaktykiRoute,
  GieldaUsaRoute: GieldaUsaRoute,
  GieldaWatchlistaRoute: GieldaWatchlistaRoute,
  GieldaIndexRoute: GieldaIndexRoute,
}

const GieldaRouteWithChildren =
  GieldaRoute._addFileChildren(GieldaRouteChildren)

interface LabRouteChildren {
  LabBacktestRoute: typeof LabBacktestRoute
  LabEveningRoute: typeof LabEveningRoute
  LabJournalRoute: typeof LabJournalRoute
  LabLedgerRoute: typeof LabLedgerRoute
  LabMorningRoute: typeof LabMorningRoute
  LabPaperRoute: typeof LabPaperRoute
  LabRaportyRoute: typeof LabRaportyRoute
  LabRiskRoute: typeof LabRiskRoute
  LabScannerRoute: typeof LabScannerRoute
  LabTelegramRoute: typeof LabTelegramRoute
  LabIndexRoute: typeof LabIndexRoute
}

const LabRouteChildren: LabRouteChildren = {
  LabBacktestRoute: LabBacktestRoute,
  LabEveningRoute: LabEveningRoute,
  LabJournalRoute: LabJournalRoute,
  LabLedgerRoute: LabLedgerRoute,
  LabMorningRoute: LabMorningRoute,
  LabPaperRoute: LabPaperRoute,
  LabRaportyRoute: LabRaportyRoute,
  LabRiskRoute: LabRiskRoute,
  LabScannerRoute: LabScannerRoute,
  LabTelegramRoute: LabTelegramRoute,
  LabIndexRoute: LabIndexRoute,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

interface SetupyRouteChildren {
  SetupyHistoriaRoute: typeof SetupyHistoriaRoute
}

const SetupyRouteChildren: SetupyRouteChildren = {
  SetupyHistoriaRoute: SetupyHistoriaRoute,
}

const SetupyRouteWithChildren =
  SetupyRoute._addFileChildren(SetupyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  DisclaimerRoute: DisclaimerRoute,
  GieldaRoute: GieldaRouteWithChildren,
  LabRoute: LabRouteWithChildren,
  LikwidacjaRoute: LikwidacjaRoute,
  LoginRoute: LoginRoute,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
  PrzeplywRoute: PrzeplywRoute,
  RegulaminRoute: RegulaminRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SentymentRoute: SentymentRoute,
  SetupyRoute: SetupyRouteWithChildren,
  SignupRoute: SignupRoute,
  SilaRoute: SilaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlownikRoute: SlownikRoute,
  SqueezeRoute: SqueezeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CoinSymbolRoute: CoinSymbolRoute,
  ApiPublicHooksAgentSimulationTickRoute:
    ApiPublicHooksAgentSimulationTickRoute,
  ApiPublicHooksLabReportsRoute: ApiPublicHooksLabReportsRoute,
  ApiPublicHooksNotifySetupsRoute: ApiPublicHooksNotifySetupsRoute,
  ApiPublicHooksScanSetupsRoute: ApiPublicHooksScanSetupsRoute,
  ApiPublicHooksVerifySetupsRoute: ApiPublicHooksVerifySetupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
